; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp07s]
platform = espressif8266
board = esp07s
framework = arduino
upload_speed = 921600
monitor_filters = esp8266_exception_decoder
monitor_speed = 115200
board_build.filesystem = littlefs
;board_build.f_cpu = 160000000L ; Overclock to 160MHz for better SoftwareSerial
extra_scripts = pre:extra.py
;build_type = debug  ; need for esp8266_exception_decoder

lib_deps =
	ottowinter/ESPAsyncWebServer-esphome
	gyverlibs/GyverOLED
	marzogh/SPIMemory
	gyverlibs/EncButton
	plerup/EspSoftwareSerial

build_flags =
	;-D SERIAL_DEBUG
