; PlatformIO Project Configuration File

[env:esp07s]
platform = espressif8266
board = esp07s
framework = arduino
upload_speed = 921600
monitor_speed = 115200
monitor_filters = esp8266_exception_decoder
;board_build.f_cpu = 160000000L ; Overclock to 160MHz for better SoftwareSerial
board_build.filesystem = littlefs
extra_scripts = pre:extra.py
;build_type = debug  ; need for esp8266_exception_decoder

lib_deps =
	ottowinter/ESPAsyncWebServer-esphome
	gyverlibs/GyverOLED
	marzogh/SPIMemory
	gyverlibs/EncButton
	slashdevin/NeoGPS

build_flags =
	;-D SERIAL_DEBUG
	; NeoGPS configuration
	-D GPS_FIX_HDOP
	; -D GPS_FIX_VDOP
	; -D GPS_FIX_PDOP
	-D NMEAGPS_PARSE_GLL
	-D NMEAGPS_PARSE_GSA
	-D NMEAGPS_PARSE_GSV
	-D NMEAGPS_PARSE_SATELLITES
	-D NMEAGPS_PARSE_SATELLITE_INFO
	;-D LAST_SENTENCE_IN_INTERVAL 2 ; enum NMEAGPS::nmea_msg_t::NMEA_GLL = 2
	-D LAST_SENTENCE_IN_INTERVAL=NMEAGPS::NMEA_GLL
